import { Message, Client } from 'discord.js';
import { SettingsService } from './../../api/settings/settings.service';
import { AvatarCommand } from '../public/avatar.commands';
import { UserCommand } from '../public/user.commands';
import { BanCommand } from './ban.commands';
import { UnbanCommand } from './unban.commands';
import { KickCommand } from './kick.commands';
import { MuteCommands } from './mute.commands';
import { UnmuteCommands } from './unmute.commands';
import { ClearCommand } from './clear.commands';
import { TimeoutCommand } from './timeout.commands';
import { ComeCommand } from './come.commands';
import { WarnCommand } from './warn.commands';
import { LockCommand } from './lock.commands';
import { UnlockCommand } from './unlock.commands';
import { MoveCommand } from './move.commands';
import { HideCommand } from './hide.commands';
import { ShowCommand } from './show.commands';
import { SayCommand } from './say.commands';
import { EmbedCommand } from './embed.commands';
import { SendCommand } from './send.commands';
import { NicknameCommand } from './nickname.commands';
import { UntimeoutCommand } from './untimeout.commands';
import { WarnRemoveCommand } from './warn_remove.commands';
import { WarningsCommand } from './warnings.commands';
import { CreditsCommand } from '../coins/credits.commands';
import { LeaderboardCommand } from '../coins/leaderboard.commands';
import { TaxCommand } from '../coins/tax.commands';
export declare class AdminPrefixHandler {
    private readonly client;
    private readonly settingsService;
    private readonly avatarCommand;
    private readonly userCommand;
    private readonly banCommand;
    private readonly unbanCommand;
    private readonly kickCommand;
    private readonly muteCommand;
    private readonly unmuteCommand;
    private readonly clearCommand;
    private readonly timeoutCommand;
    private readonly warnCommand;
    private readonly lockCommand;
    private readonly unlockCommand;
    private readonly moveCommand;
    private readonly hideCommand;
    private readonly showCommand;
    private readonly sayCommand;
    private readonly comeCommand;
    private readonly embedCommand;
    private readonly sendCommand;
    private readonly nicknameCommand;
    private readonly untimeoutCommand;
    private readonly warnRemoveCommand;
    private readonly warningsCommand;
    private readonly creditsCommand;
    private readonly leaderboardCommand;
    private readonly taxCommand;
    private readonly logger;
    constructor(client: Client, settingsService: SettingsService, avatarCommand: AvatarCommand, userCommand: UserCommand, banCommand: BanCommand, unbanCommand: UnbanCommand, kickCommand: KickCommand, muteCommand: MuteCommands, unmuteCommand: UnmuteCommands, clearCommand: ClearCommand, timeoutCommand: TimeoutCommand, warnCommand: WarnCommand, lockCommand: LockCommand, unlockCommand: UnlockCommand, moveCommand: MoveCommand, hideCommand: HideCommand, showCommand: ShowCommand, sayCommand: SayCommand, comeCommand: ComeCommand, embedCommand: EmbedCommand, sendCommand: SendCommand, nicknameCommand: NicknameCommand, untimeoutCommand: UntimeoutCommand, warnRemoveCommand: WarnRemoveCommand, warningsCommand: WarningsCommand, creditsCommand: CreditsCommand, leaderboardCommand: LeaderboardCommand, taxCommand: TaxCommand);
    onMessageCreate([message]: [Message]): Promise<void>;
    private readonly COMMAND_PERMISSIONS;
    private dispatch;
}
